<?php

namespace App\Http\Controllers;

use App\Models\Table;
use App\Models\TableRequest;
use App\Models\TableSession;

// use Illuminate\Http\Request;

class TableController extends Controller
{
    // Getting table access 
    public function GetTableAccess(string $tableNum){
        // checking status that the table has any ongoing session
        $hasSession = TableSession::where('table_number', $tableNum)
            ->where('active', true)
            ->where('expires_at', '>', now())->first();
        // if yes then redirect it to menu page with their table number and token
        if($hasSession){
            return redirect()
                ->route('getMenu', ['tableNum' => $hasSession->table_number, 'token' => $hasSession->session_token]);
        } else {
            // if session not exist the redirect to wait for approval page to get new token for table access
            return redirect()->route('WaitWhileApproving',$tableNum);
        }
    }

    // wait for approval page 
    public function WaitForApproval(string $tableNum){
        // checking that there is any table is created. if not then redirect to the homepage
        $tableInfo = Table::where('table_number', $tableNum)->first();
        if($tableInfo==NULL){
            return redirect()->route('HomePage');
        }
        // Prevents Duplicate Requests by Updating the request made time 
        $request = TableRequest::updateOrCreate(
            [
                'table_id' => $tableInfo->id,
                'request_status' => 'pending',
                'status_updated_at' => NULL,
            ],
            [
                'made_at' => now()
            ]
        );
        return view('customer.wait-for-table', ['reqId' => $request->id]);
    }

    // checking request status is approved or rejected
    public function tableStatus(string $id) {
        // finding request details by request id
        $req = TableRequest::with('tableinfo')->findOrFail($id);
        // if request is approved then fetching the session details generated by admin and sending as a response
        if ($req->request_status === 'approved') {
            $session = TableSession::find($req->session_id);
            return response()->json([
                'status' => 'approved',
                'session_token' => $session->session_token,
                'table_number' => $req->tableinfo->table_number
            ]);
        }
        // returning request status as a response if request is not approved
        return response()->json([
            'status' => $req->request_status
        ]);
    }
}
